// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncuoycrxqtvdkmbeoaxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdW95Y3J4cXR2ZGttYmVvYXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTQ2OTQsImV4cCI6MjA2MTc5MDY5NH0.jGsAmVd12_cImssHXloRH0ajsp-ea_1GyRMxNrulpeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);